server.port=8087
spring.application.name=simulator

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# UUID-ul unui device real din tabela device-service.devices
sim.device-id=838144ce-a17b-4672-8204-34f2d1c8461d

# intervalul la care trimite (ms)
sim.interval=10000
