server.port=8087
spring.application.name=simulator

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# UUID-ul unui device real din tabela device-service.devices
sim.device-id=c0b3ed45-88c9-404a-8c5e-8701e8bd1538

# intervalul la care trimite (ms)
sim.interval=10000
sim.ws-url=http://localhost/ws