entryPoints:
  web:
    address: ":80"

api:
  dashboard: true
  insecure: true

providers:
  swarm:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: "/etc/traefik/dynamic.yml"
    watch: true

log:
  level: INFO
