# ===============================
# Application
# ===============================
spring.application.name=load-balancing-service
server.port=8088

# ===============================
# RabbitMQ connection
# ===============================
spring.rabbitmq.host=${RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=20
spring.rabbitmq.listener.simple.retry.initial-interval=3000
spring.rabbitmq.listener.simple.retry.multiplier=1.5
spring.rabbitmq.listener.simple.retry.max-interval=15000

spring.rabbitmq.connection-timeout=60000
# ===============================
# Queues
# ===============================

# Queue central (input unic din simulator)
rabbitmq.device.queue=device_data_queue

# Prefix pentru ingest queues
rabbitmq.ingest.queue.prefix=ingest-

# Numarul de replici Monitoring Service
monitoring.replicas=6

# ===============================
# Logging
# ===============================
logging.level.org.springframework.amqp=INFO
logging.level.com.example.loadbalancing=DEBUG
