spring.application.name=websocket-service
# ===============================
# Application
# ===============================
server.port=8085

# ===============================
# WebSocket / STOMP
# ===============================
spring.websocket.enabled=true

# ===============================
# Logging (util pentru debug WS)
# ===============================
logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.messaging=DEBUG
