spring.application.name=monitoring-service


###############################################
### DATABASE CONFIGURATION ###
###############################################
database.ip=${DB_IP:localhost}
database.port=${DB_PORT:5432}
database.user=${DB_USER}
database.password=${DB_PASSWORD}
database.name=${DB_DBNAME:monitoring_db}

spring.datasource.url=jdbc:postgresql://${database.ip}:${database.port}/${database.name}?sslmode=disable
spring.datasource.username=${database.user}
spring.datasource.password=${database.password}

spring.sql.init.platform=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


###############################################
### RABBITMQ CONFIGURATION ###
###############################################
spring.rabbitmq.host=${RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}


spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=20
spring.rabbitmq.listener.simple.retry.initial-interval=3000
spring.rabbitmq.listener.simple.retry.multiplier=1.5
spring.rabbitmq.listener.simple.retry.max-interval=15000

spring.rabbitmq.connection-timeout=60000



###############################################
### SERVER CONFIGURATION ###
###############################################
server.port=${PORT:8084}


###############################################
### LOGGING CONFIGURATION ###
###############################################
logging.level.root=warn
logging.level.org.springframework=warn
logging.level.com.example.monitoring=debug


###############################################
### CORS CONFIGURATION ###
###############################################
spring.mvc.cors.mappings.[/**].allowed-origins=*
spring.mvc.cors.mappings.[/**].allowed-methods=*
spring.mvc.cors.mappings.[/**].allowed-headers=*

###############################################
### LOAD BALANCING (INGEST QUEUE) ###
###############################################
monitoring.ingest.queue=${INGEST_QUEUE:ingest-1}
websocket.service.url=${WEBSOCKET_SERVICE_URL:http://websocket-service:8085}

# ===============================
# Hikari (IMPORTANT for replicas)
# ===============================
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
